# Generated by Django 6.0.7 on 2026-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_preference',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
