# Generated by Django 6.0.7 on 2026-07-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_user_gender_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
