# Generated by Django 6.0.7 on 2026-07-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_background_url'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='music.track'),
        ),
        migrations.AddField(
            model_name='user',
            name='music_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
