# Generated by Django 6.0.7 on 2026-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('repost', 'Repost'), ('message', 'Message'), ('badge', 'Badge'), ('blast', 'Blast'), ('concert_invite', 'Concert Invite'), ('concert_alert', 'Concert Alert')], max_length=20),
        ),
    ]
