# Generated by Django 6.0.7 on 2026-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningactivity',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
