# Generated by Django 6.0.7 on 2026-07-28 19:58

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_listeningactivity_duration_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('ticket_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'concerts',
                'ordering': ['date_time'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ConcertAttendance',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='social.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'concert_attendances',
                'unique_together': {('user', 'concert')},
            },
        ),
    ]
