# Generated by Django 6.0.7 on 2026-07-10 09:56

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image_url', models.URLField(blank=True, default='')),
                ('genres', models.JSONField(blank=True, default=list)),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('lastfm_url', models.URLField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('popularity', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'artists',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('album_name', models.CharField(blank=True, default='', max_length=500)),
                ('album_art_url', models.URLField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('preview_url', models.URLField(blank=True, default='')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('spotify_uri', models.CharField(blank=True, default='', max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('audio_features', models.JSONField(blank=True, default=dict)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('release_date', models.CharField(blank=True, default='', max_length=20)),
                ('is_explicit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.artist')),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='VinylWallItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinyl_appearances', to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinyl_wall', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vinyl_wall_items',
                'ordering': ['position'],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
